[package]
version = "0.1.0"
title = "object centering"

[dependencies]
"omni.kit.mainwindow" = {}

[python.pipapi] 
requirements = [
    "numpy",
]
use_online_index = true

[[python.module]]
name = "cn.appincloud.objectcentering"
